### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by hfiguiere** [lavabit/libdime#10]
there is no license in the repository. This make it impossible to use the library.

**Comment by LBiv** [comment]
Hey, sorry about this. Ladar forgot to provide one for me to add, I will bug him about this as soon as we're in contact.

**Comment by deepfire** [comment]
> Ladar forgot to provide one

Sounds extremely improbable.

My money is on that it is intentional, for some reason.

**Comment by LBiv** [comment]
He wasn't decided on one and was in a hurry to Germany.

**Comment by LBiv** [comment]
It's coming shortly.

**Comment by LBiv** [comment]
License added.
