### ISSUE TITLE
missing NUL byte

### ISSUE THREAD

**Issue by MegaManSec** [lavabit/libdime#3]
Hi,

In /lib/dmtp.c:

1358                        nread = recv(session->_fd, &(session->_inbuf[session->_inpos]), nleft, 0);

recv() does not NUL terminate.

but:

1352        while (nleft && (!(lbreak = strstr((char *)session->_inbuf, "\r\n")))) {

strstr() expects a NUL terminated string.

**Comment by rillig** [comment]
The NUL byte is not missing. The last byte of the buffer is always '\0', therefore string operations are valid.
