### ISSUE TITLE
Documentation for Builds

### ISSUE THREAD

**Issue by flounders** [lavabit/libdime#31]
This has to do with the develop branch, but the current instructions for building in the Readme and the Quickstart guide are out of date. I'd be happy to update the documentation myself but I want to make sure I have the build process right.

```
$ libtoolize
$ aclocal
$ automake --add-missing
$ ./configure
$ make
```

If that's the right process then I will need to file another issue as the SSL library header is for some reason not being included (or the declaration for X509_check_host is missing) before libs/signet-resolver/ssl.c is built.

**Comment by mikezackles** [comment]
Thank you -- yes, these docs need to be updated.  The intended build process is

```
autoreconf --install
./configure
make
```

Also, please note that the RHEL openssl build is currently unsupported as I'm pretty sure it does not yet enable secp256k1.  The develop build is currently known to work on Arch Linux and OS X.  Please do file another issue if you're still having problems.

**Comment by mikezackles** [comment]
A few more notes:

[Arch PKGBUILD](https://gist.github.com/mikezackles/ea1415560a43f881b604)
[OS X Homebrew formula](https://gist.github.com/mikezackles/39803d5d12b6b55e9af5)
[Info on RHEL and secp256k1](https://www.bfccomputing.com/bitcoin-and-curve-secp256k1-on-fedora/)

Out-of-source builds are also supported for dev.  For example, a debug build could look like:

```
mkdir build
cd build
../configure CFLAGS="-g -O0"
make check
```

**Comment by flounders** [comment]
I just tried those instructions on my Arch machine and it builds without any problems. On my Ubuntu machine, which I was initial doing testing with, it still fails on that one function. I'll open a separate issue for that.
