### ISSUE TITLE
memory leaks

### ISSUE THREAD

**Issue by MegaManSec** [lavabit/libdime#6]
in
/lib/cache.c:
 862                        RET_ERROR_PTR(ERR_UNSPEC, "unable to create new cached object");
leaks 'found'

1266                                RET_ERROR_INT(ERR_NOMEM, NULL);
leaks 'cfd'

692                        RET_ERROR_PTR(ERR_UNSPEC, "unable to create new cached object");
leaks 'found'(could this code be optimized into L862?)

1461                                                RET_ERROR_INT(ERR_UNSPEC, "error serializing cached data to file");
leaks 'cfile'

1266                                RET_ERROR_INT(ERR_NOMEM, NULL);
and
1275                        RET_ERROR_INT(ERR_UNSPEC, "unable to read contents of object cache");
and
1305                        RET_ERROR_INT(ERR_NOMEM, NULL);
and
1232                        RET_ERROR_INT(ERR_UNSPEC, "unable to create cache file");
and
1235                return 0;
and
1254                                RET_ERROR_INT(ERR_UNSPEC, "reached unexpected end of cache data file");
leaks 'cfile'

**Comment by LBiv** [comment]
Fixed where appropriate.
