### ISSUE TITLE
memory leaks in dns.c

### ISSUE THREAD

**Issue by MegaManSec** [lavabit/libdime#7]
and in /lib/dns.c:
1764                        RET_ERROR_PTR(ERR_UNSPEC, "error occurred parsing TXT record answer");
and
1720                        if (!(result = malloc(rdleft+1))) {
and
1672                        RET_ERROR_PTR(ERR_UNSPEC, "error occurred parsing TXT record answer");
leaks 'result'

545                        RET_ERROR_INT(ERR_UNSPEC, "unable to import DNS root key entry");
and
540                        RET_ERROR_INT(ERR_UNSPEC, "could not get tag value for DNSKEY");
and
527                        RET_ERROR_INT(ERR_UNSPEC, "failed to extract public key from DNSKEY RR");
and
523                        RET_ERROR_INT(ERR_UNSPEC, "failed to extract base64 encoded public key from root key config file");
and
510                        RET_ERROR_INT(ERR_UNSPEC, "encountered unexpected end of line");
and
500                        RET_ERROR_INT(ERR_UNSPEC, "encountered unexpected end of line");
and
490                        RET_ERROR_INT(ERR_UNSPEC, "encountered unexpected end of line");
and
482                        RET_ERROR_INT_FMT(ERR_UNSPEC, "encountered unexpected algorithm: %u", algorithm);
and
478                        RET_ERROR_INT_FMT(ERR_UNSPEC, "encountered unexpected protocol in DNS key file: %u", protocol);
and
474                        RET_ERROR_INT_FMT(ERR_UNSPEC, "encountered unexpected key flags in DNS key file: %u", flags);

leaks 'fp'

**Comment by LBiv** [comment]
fixed
